// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAyuerMheHvDTM7xpIft3F2-qwIzAOSd88',
    appId: '1:587716803801:web:08ff8811f454e79ee6d2c8',
    messagingSenderId: '587716803801',
    projectId: 'firefight-equip-app',
    authDomain: 'firefight-equip-app.firebaseapp.com',
    storageBucket: 'firefight-equip-app.appspot.com',
    measurementId: 'G-RYKHFQH8DM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCrVbaGu7RmD0lrniNt5Wd_bHa5EkD8nnI',
    appId: '1:587716803801:android:1594ff2472b3bf45e6d2c8',
    messagingSenderId: '587716803801',
    projectId: 'firefight-equip-app',
    storageBucket: 'firefight-equip-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBoLDiI2SUguhRdKTP-1nCYB6BysFL0beI',
    appId: '1:587716803801:ios:3aae03c441dd96f1e6d2c8',
    messagingSenderId: '587716803801',
    projectId: 'firefight-equip-app',
    storageBucket: 'firefight-equip-app.appspot.com',
    iosClientId: '587716803801-nub22mb1sq8dkefdf0nl657evcldk2qr.apps.googleusercontent.com',
    iosBundleId: 'com.example.firefightEquip',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBoLDiI2SUguhRdKTP-1nCYB6BysFL0beI',
    appId: '1:587716803801:ios:3aae03c441dd96f1e6d2c8',
    messagingSenderId: '587716803801',
    projectId: 'firefight-equip-app',
    storageBucket: 'firefight-equip-app.appspot.com',
    iosClientId: '587716803801-nub22mb1sq8dkefdf0nl657evcldk2qr.apps.googleusercontent.com',
    iosBundleId: 'com.example.firefightEquip',
  );
}
